import Header from "@/Components/Layouts/Header";
// import './globals.css'
import { Inter } from "next/font/google";
import "@/Assets/Styles/404Errorpage/Errorpage.scss";
import '@/Assets/Styles/AboutUs/AboutUs.scss';
import "@/Assets/Styles/Announcement/Announcement.scss";
import "@/Assets/Styles/Benchmarkindices/Benchmarkindices.scss";
import "@/Assets/Styles/Cadmin/Cadmin.scss";
import "@/Assets/Styles/Career/Career.scss";
import "@/Assets/Styles/CareerJobDescription/CareerJobDescription.scss";
import "@/Assets/Styles/Carousel/Carousel.scss";
import "@/Assets/Styles/Common/Common.scss";
import "@/Assets/Styles/Contactus/Contactus.scss";
import "@/Assets/Styles/Cookie/Cookie.scss";
import "@/Assets/Styles/CookiePolicy/CookiePolicy.scss";
import "@/Assets/Styles/DataPrivacy/DataPrivacy.scss";
import "@/Assets/Styles/Home/Home.scss";
import "@/Assets/Styles/Indices/Indices.scss";
import "@/Assets/Styles/IndivisualIndexName/IndivisualIndexName.scss";
import "@/Assets/Styles/IndxxServices/IndxxServices.scss";
import "@/Assets/Styles/ITICS/ITICS.scss";
import "@/Assets/Styles/News&Research/NewsResearch.scss";
import "@/Assets/Styles/NewsAndResearchIndsider/NewsAndResearchIndsider.scss";
import "@/Assets/Styles/Offering/Offering.scss";
import "@/Assets/Styles/PressRelease/PressRelease.scss";
import "@/Assets/Styles/ThankYou/ThankYou.scss";
import "@/Assets/Styles/Graph.scss";
import Footer from "@/Components/Layouts/Footer";
import { Box } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Indxx – Indexing Redefined",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <Box className="centerContainer">{children}</Box>
        <Footer />
      </body>
    </html>
  );
}
