import Home from '@/Pages/Home/Home'
import React from 'react'
import styles from "./page.module.css";


// export const metadata = {
//   title: "Layout Title 2",
//   description: "Generated by create next app",
// };

export default function page() {
  return (
    <><Home/></>
  )
}
